#ifndef MENU_DEFINES_H
#define MENU_DEFINES_H


#define INIT_VALUE "0"
#define PRESSED 1
#define BUTTON_RIGHT "RIGHT"
#define BUTTON_LEFT "LEFT"
#define BUTTON_OK "OK"
#define BUTTON_CLOSE_POPUP "CLOSE_POPUP"
#define BUTTON_BACK "BACK"
#define BUTTON_UP "UP"
#define BUTTON_DOWN "DOWN"
#define BUTTON_EMPTY "EMPTY"
#define MENU_RU_FILENAME "menu_ru"
#define TRANSLATOR_DIRECTORY ":/Translator"

#define INIT_VAL_0 0

#define INVALID_SIGNAL "--"
#define TYRE_FAULT_COLOR "yellow"

#define MENU_RANGE_SEPERATOR ":"
#define INVALID_TEMPERATURE "-- " //"-- °C"
#define INVALID_PRESSURE "-- бар (bar)"
#define INVALID_PERCENTAGE "-- " //"-- %"
#define TIMEOUT_COLOR "red"
#define MAX_TIMER_COUNTER 50000

#define UOM_DEGREE_CELCIUS " °C"
#define UOM_BAR " bar"
#define UOM_CONSUMPTION " L/h"
#define UOM_KM " L/100KM"
#define UOM_VOLTAGE " V"
#define UOM_PERCENTAGE " %"
#define UOM_PRESSURE " бар (bar)"

#define RST_AVERAGE_FUEL_CONSUMPTION "  0 L/100KM"

#define MENU_PARAMETERS "PARAMETERS"
#define MENU_DIAGNOSTICS "DIAGNOSTICS"
#define MENU_SETTINGS "SETTINGS"
#define MENU_SERVICES "SERVICES"

#define MENU_ENGINE "ENGINE"
#define MENU_TRANSMISSION "TRANSMISSION"
#define MENU_BATTERY "BATTERY"
#define MENU_PNEUMATIC_SYSTEM "PNEUMATIC_SYSTEM"
#define TYRE_PRESSURE_AND_TEMPERATURE "TYRE_PRESSURE_AND_TEMPERATURE"
#define MENU_BRAKE_PADS_WEAR "BRAKE_PADS_WEAR"
#define MENU_WIPERS "WIPERS"
#define MENU_REAGENT_ADBLUE "REAGENT_ADBLUE"

#define ENGINE_HEADER "ENGINE"
#define TRANSMISSION_HEADER "TRANSMISSION"
#define BATTERY_HEADER "BATTERY"
#define PNEUMATIC_SYSTEM_HEADER "PNEUMATIC_SYSTEM"
#define TYRE_PRESSURE_AND_TEMPERATURE_HEADER "TYRE_PRESSURE_AND_TEMPERATURE"
#define BRAKE_PADS_WEAR_HEADER "BRAKE_PADS_WEAR"
#define WIPERS_HEADER "WIPERS"
#define REAGENT_ADBLUE_HEADER "REAGENT_ADBLUE"

#define COOLANT_TEMPERATURE "COOLANT_TEMPERATURE"
#define OIL_TEMPERATURE_ENGINE "OIL_TEMPERATURE_ENGINE"
#define OIL_PRESSURE "OIL_PRESSURE"
#define INSTANT_FUEL_CONSUMPTION "INSTANT_FUEL_CONSUMPTION "
#define AVG_FUEL_CONSUMPTION "AVERAGE_FUEL_CONSUMPTION"

#define OIL_TEMPERATURE_TRANSMISSION "OIL_TEMPERATURE_TRANSMISSION"
#define OIL_TEMPERATURE_IN_HYDRAULIC_RETARDER "OIL_TEMPERATURE_IN_HYDRAULIC_RETARDER"
#define OUTPUT_SHAFT_SPEED "OUTPUT_SHAFT_SPEED"

#define VOLTAGE "VOLTAGE"
#define CURRENT_1 "CURRENT_1"
#define CURRENT_2 "CURRENT_2"

#define INTERMEDIATE_AXLE_BRAKING_CIRCUIT "INTERMEDIATE_AXLE_BRAKING_CIRCUIT"
#define REAR_AXLE_BRAKING_CIRCUIT "REAR_AXLE_BRAKING_CIRCUIT"
#define FRONT_AXLE_BRAKING_CIRCUIT "FRONT_AXLE_BRAKING_CIRCUIT"
#define PARKING_BRAKE "PARKING_BRAKE"
#define AUXILIARY_EQUIPMENT "AUXILIARY_EQUIPMENT"

#define WASHER_FLUID_LEVEL "WASHER_FLUID_LEVEL"
#define NUMBER_OF_OPERATIONS "NUMBER_OF_OPERATIONS"

#define ADBLUE_LEVEL "ADBLUE_LEVEL"
#define ADBLUE_TEMPERATURE "ADBLUE_TEMPERATURE"

#define TYRE1_TEMPERATURE "TYRE1_TEMPERATURE"
#define TYRE2_TEMPERATURE "TYRE2_TEMPERATURE"
#define TYRE3_TEMPERATURE "TYRE3_TEMPERATURE"
#define TYRE4_TEMPERATURE "TYRE4_TEMPERATURE"
#define TYRE5_TEMPERATURE "TYRE5_TEMPERATURE"
#define TYRE6_TEMPERATURE "TYRE6_TEMPERATURE"
#define TYRE7_TEMPERATURE "TYRE7_TEMPERATURE"
#define TYRE8_TEMPERATURE "TYRE8_TEMPERATURE"
#define TYRE9_TEMPERATURE "TYRE9_TEMPERATURE"
#define TYRE10_TEMPERATURE "TYRE10_TEMPERATURE"

#define TYRE1_PRESSURE "TYRE1_PRESSURE"
#define TYRE2_PRESSURE "TYRE2_PRESSURE"
#define TYRE3_PRESSURE "TYRE3_PRESSURE"
#define TYRE4_PRESSURE "TYRE4_PRESSURE"
#define TYRE5_PRESSURE "TYRE5_PRESSURE"
#define TYRE6_PRESSURE "TYRE6_PRESSURE"
#define TYRE7_PRESSURE "TYRE7_PRESSURE"
#define TYRE8_PRESSURE "TYRE8_PRESSURE"
#define TYRE9_PRESSURE "TYRE9_PRESSURE"
#define TYRE10_PRESSURE "TYRE10_PRESSURE"

#define TYRE1_COLOR "TYRE1_COLOR"
#define TYRE2_COLOR "TYRE2_COLOR"
#define TYRE3_COLOR "TYRE3_COLOR"
#define TYRE4_COLOR "TYRE4_COLOR"
#define TYRE5_COLOR "TYRE5_COLOR"
#define TYRE6_COLOR "TYRE6_COLOR"
#define TYRE7_COLOR "TYRE7_COLOR"
#define TYRE8_COLOR "TYRE8_COLOR"
#define TYRE9_COLOR "TYRE9_COLOR"
#define TYRE10_COLOR "TYRE10_COLOR"

#define FIRST_BRAKEPADS "FIRST_BRAKEPADS"
#define SECOND_BRAKEPADS "SECOND_BRAKEPADS"
#define THIRD_BRAKEPADS "THIRD_BRAKEPADS"
#define FOURTH_BRAKEPADS "FOURTH_BRAKEPADS"
#define FIFTH_BRAKEPADS "FIFTH_BRAKEPADS"
#define SIXTH_BRAKEPADS "SIXTH_BRAKEPADS"

#define FAILURES "Failures"
#define EMERGENCY_CRANES "Emergency Cranes"
#define DOOR_VALVES "Door Valves"
#define DOOR_SENSORS "Door Sensors"
#define EMERGENCY_HAMMERS "Emergency Hammers"
#define FIRE_EXTINGUISHERS "Fire Extinguishers"
#define HEATERS "Heaters"
#define HEATING_SYSTEM_VALVES "Heating System Valves"
#define LIGHTING_EQUIPMENTS "LIGHTING_EQUIPMENTS"

#define FAILURES_HEADER "FAILURES"
#define EMERGENCY_CRANES_HEADER "EMERGENCY_CRANES"
#define DOOR_VALVES_HEADER "DOOR_VALVES"
#define DOOR_SENSORS_HEADER "DOOR_SENSORS"
#define EMERGENCY_HAMMERS_HEADER "EMERGENCY_HAMMERS"
#define FIRE_EXTINGUISHERS_HEADER "FIRE_EXTINGUISHERS"
#define HEATERS_HEADER "HEATERS"
#define HEATING_SYSTEM_VALVES_HEADER "HEATING_SYSTEM_VALVES"
#define LIGHTING_EQUIPMENTS_HEADER "LIGHTING_EQUIPMENTS"

#define FAILURES_FIRE_EXTINGUISHER_SYSTEM "FAILURES_FIRE_EXTNIGUISHER_SYSTEM"
#define FAILURES_BRAKE_SYSTEM "FAILURES_BRAKE_SYSTEM"
#define FAILURES_PNEUMATIC_SYSTEM "FAILURES_PNEUMATIC_SYSTEM"
#define FAILURES_PROPULSION_SYSTEM "FAILURES_PROPULSION_SYSTEM"
#define FAILURES_TRANSMISSION "FAILURES_TRANSMISSION"
#define FAILURES_TACHOGRAPH "FAILURES_TACHOGRAPH"
#define FAILURES_TIREPRESSURETEMP "FAILURES_TIREPRESSURETEMP"
#define FAILURES_ADAS_DRIVER_ASSIST "FAILURES_ADAS_DRIVER_ASSIST"
#define NO_FAILURES "NO_FAILURES"

#define FAILURES_ERROR_COUNT "FAILURES_ERROR_COUNT"
#define FAILURES_ERROR_FIRE_EXTINGUISHERS_COUNT "FAILURES_ERROR_FIRE_EXTINGUISHERS_COUNT"

#define FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1002 "FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1002"
#define FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1003 "FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1003"
#define FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1004 "FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1004"
#define FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1005 "FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1005"
#define FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1006 "FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1006"
#define FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1007 "FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1007"
#define FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1008 "FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1008"
#define FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1009 "FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1009"
#define FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1010 "FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1010"
#define FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1011 "FAILURES_FIRE_EXTINGUISHER_SYSTEM_ERROR_CODE_1011"

#define FAILURES_ERROR_BRAKE_SYSTEM_COUNT "FAILURES_ERROR_BRAKE_SYSTEM_COUNT"
#define FAILURES_BRAKE_SYSTEM_ERROR_CODE_3001 "FAILURES_BRAKE_SYSTEM_ERROR_CODE_3001"
#define FAILURES_BRAKE_SYSTEM_ERROR_CODE_3002 "FAILURES_BRAKE_SYSTEM_ERROR_CODE_3002"
#define FAILURES_BRAKE_SYSTEM_ERROR_CODE_3003 "FAILURES_BRAKE_SYSTEM_ERROR_CODE_3003"

#define FAILURES_ERROR_PNEUMATIC_SYSTEM_COUNT "FAILURES_ERROR_PNEUMATIC_SYSTEM_COUNT"
#define FAILURES_PNEUMATIC_SYSTEM_ERROR_CODE_4001 "FAILURES_PNEUMATIC_SYSTEM_ERROR_CODE_4001"
#define FAILURES_PNEUMATIC_SYSTEM_ERROR_CODE_4002 "FAILURES_PNEUMATIC_SYSTEM_ERROR_CODE_4002"
#define FAILURES_PNEUMATIC_SYSTEM_ERROR_CODE_4003 "FAILURES_PNEUMATIC_SYSTEM_ERROR_CODE_4003"

#define FAILURES_ERROR_PROPULSION_SYSTEM_COUNT "FAILURES_ERROR_PROPULSION_SYSTEM_COUNT"
#define FAILURES_PROPULSION_SYSTEM_ERROR_CODE_5001 "FAILURES_PROPULSION_SYSTEM_ERROR_CODE_5001"
#define FAILURES_PROPULSION_SYSTEM_ERROR_CODE_5002 "FAILURES_PROPULSION_SYSTEM_ERROR_CODE_5002"
#define FAILURES_PROPULSION_SYSTEM_ERROR_CODE_5003 "FAILURES_PROPULSION_SYSTEM_ERROR_CODE_5003"

#define FAILURES_ERROR_TRANSMISSION_SYSTEM_COUNT "FAILURES_ERROR_TRANSMISSION_SYSTEM_COUNT"
#define FAILURES_TRANSMISSION_ERROR_CODE_6001 "FAILURES_TRANSMISSION_ERROR_CODE_6001"
#define FAILURES_TRANSMISSION_ERROR_CODE_6002 "FAILURES_TRANSMISSION_ERROR_CODE_6002"
#define FAILURES_TRANSMISSION_ERROR_CODE_6003 "FAILURES_TRANSMISSION_ERROR_CODE_6003"

#define FAILURES_ERROR_TACHOGRAPH_SYSTEM_COUNT "FAILURES_ERROR_TACHOGRAPH_SYSTEM_COUNT"
#define FAILURES_TACHOGRAPH_ERROR_CODE_7001 "FAILURES_TACHOGRAPH_ERROR_CODE_7001"
#define FAILURES_TACHOGRAPH_ERROR_CODE_7003 "FAILURES_TACHOGRAPH_ERROR_CODE_7003"

#define FAILURES_ERROR_TIREPRESSURETEMP_MONITOR_SYSTEM_COUNT "FAILURES_ERROR_TIREPRESSURETEMP_MONITOR_SYSTEM_COUNT"
#define FAILURES_TIREPRESSURETEMP_MONITOR_ERROR_CODE_10001 "FAILURES_TIREPRESSURETEMP_MONITOR_ERROR_CODE_10001"
#define FAILURES_TIREPRESSURETEMP_MONITOR_ERROR_CODE_10002 "FAILURES_TIREPRESSURETEMP_MONITOR_ERROR_CODE_10002"

#define FAILURES_ERROR_ADAS_DRIVER_ASSIST_SYSTEM_COUNT "FAILURES_ERROR_ADAS_DRIVER_ASSIST_SYSTEM_COUNT"
#define FAILURES_ADAS_DRIVER_ASSIST_ERROR_CODE_13001 "FAILURES_ADAS_DRIVER_ASSIST_ERROR_CODE_13001"

#define EMERGENCY_CRANE_1 "EMERGENCY_CRANE_1"
#define EMERGENCY_CRANE_2 "EMERGENCY_CRANE_2"
#define EMERGENCY_CRANE_3 "EMERGENCY_CRANE_3"
#define EMERGENCY_CRANE_4 "EMERGENCY_CRANE_4"
#define EMERGENCY_CRANE_5 "EMERGENCY_CRANE_5"
#define EMERGENCY_CRANE_6 "EMERGENCY_CRANE_6"
#define EMERGENCY_CRANE_7 "EMERGENCY_CRANE_7"
#define EMERGENCY_CRANE_8 "EMERGENCY_CRANE_8"

#define DOOR_VALVE_1 "DOOR_VALVE_1"
#define DOOR_VALVE_2 "DOOR_VALVE_2"
#define DOOR_VALVE_3 "DOOR_VALVE_3"
#define DOOR_VALVE_4 "DOOR_VALVE_4"
#define DOOR_VALVE_5 "DOOR_VALVE_5"
#define DOOR_VALVE_6 "DOOR_VALVE_6"
#define DOOR_VALVE_7 "DOOR_VALVE_7"
#define DOOR_VALVE_8 "DOOR_VALVE_8"

#define DOOR_SENSOR_1 "DOOR_SENSOR_1"
#define DOOR_SENSOR_2 "DOOR_SENSOR_2"
#define DOOR_SENSOR_3 "DOOR_SENSOR_3"
#define DOOR_SENSOR_4 "DOOR_SENSOR_4"
#define DOOR_SENSOR_5 "DOOR_SENSOR_5"
#define DOOR_SENSOR_6 "DOOR_SENSOR_6"
#define DOOR_SENSOR_7 "DOOR_SENSOR_7"
#define DOOR_SENSOR_8 "DOOR_SENSOR_8"
#define DOOR_SENSOR_9 "DOOR_SENSOR_9"
#define DOOR_SENSOR_10 "DOOR_SENSOR_10"
#define DOOR_SENSOR_11 "DOOR_SENSOR_11"
#define DOOR_SENSOR_12 "DOOR_SENSOR_12"
#define DOOR_SENSOR_13 "DOOR_SENSOR_13"
#define DOOR_SENSOR_14 "DOOR_SENSOR_14"
#define DOOR_SENSOR_15 "DOOR_SENSOR_15"
#define DOOR_SENSOR_16 "DOOR_SENSOR_16"

#define EMERGENCY_HAMMERS_1 "EMERGENCY_HAMMERS_1"
#define EMERGENCY_HAMMERS_2 "EMERGENCY_HAMMERS_2"
#define EMERGENCY_HAMMERS_3 "EMERGENCY_HAMMERS_3"
#define EMERGENCY_HAMMERS_4 "EMERGENCY_HAMMERS_4"
#define EMERGENCY_HAMMERS_5 "EMERGENCY_HAMMERS_5"

#define FIRE_EXTINGUISHER_1 "FIRE_EXTINGUISHER_1"
#define FIRE_EXTINGUISHER_2 "FIRE_EXTINGUISHER_2"
#define FIRE_EXTINGUISHER_3 "FIRE_EXTINGUISHER_3"

#define HEATERS_1 "HEATERS_1"
#define HEATERS_2 "HEATERS_2"
#define HEATERS_3 "HEATERS_3"
#define HEATERS_4 "HEATERS_4"
#define HEATERS_5 "HEATERS_5"
#define HEATERS_6 "HEATERS_6"
#define HEATERS_7 "HEATERS_7"
#define HEATERS_8 "HEATERS_8"
#define HEATERS_9 "HEATERS_9"

#define HEATING_SYSTEM_VALVE_1 "HEATING_SYSTEM_VALVE_1"
#define HEATING_SYSTEM_VALVE_2 "HEATING_SYSTEM_VALVE_2"
#define HEATING_SYSTEM_VALVE_3 "HEATING_SYSTEM_VALVE_3"
#define HEATING_SYSTEM_VALVE_4 "HEATING_SYSTEM_VALVE_4"
#define HEATING_SYSTEM_VALVE_5 "HEATING_SYSTEM_VALVE_5"
#define HEATING_SYSTEM_VALVE_6 "HEATING_SYSTEM_VALVE_6"
#define HEATING_SYSTEM_VALVE_7 "HEATING_SYSTEM_VALVE_7"
#define HEATING_SYSTEM_VALVE_8 "HEATING_SYSTEM_VALVE_8"
#define HEATING_SYSTEM_VALVE_9 "HEATING_SYSTEM_VALVE_9"

#define TESTING_LIGHTING_EQUIPMENT "TESTING_LIGHTING_EQUIPMENT"
#define POSITION_LIGHT "POSITION_LIGHT"
#define LOW_BEAM "LOW_BEAM"
#define HIGH_BEAM "HIGH_BEAM"
#define TURN_SIGNALS "TURN_SIGNALS"
#define DLR "DLR"
#define FRONT_FOG_LAMP "FRONT_FOG_LAMP"
#define REAR_FOG_LAMP "REAR_FOG_LAMP"
#define REVERSE_LIGHTS "REVERSE_LIGHTS"
#define LIGHTS "LIGHTS"

// settings
#define HEATING_SYSTEM "Heating System"
#define DASHBOARD "DASHBOARD"
#define LIGHT_AND_RAIN_SENSOR "LIGHT_AND_RAIN_SENSOR"
#define CLIMATE_CONTROL_IN_DRIVER_CAB "CLIMATE_CONTROL_IN_DRIVER_CAB"

#define HEATING_SYSTEM_HEADER "HEATING_SYSTEM"
#define DASHBOARD_HEADER "DASHBOARD"
#define LIGHT_AND_RAIN_SENSOR_HEADER "LIGHT_AND_RAIN_SENSOR"
#define CLIMATE_CONTROL_IN_DRIVER_CAB_HEADER "CLIMATE_CONTROL_IN_DRIVER_CAB"

#define INSTALLATION_TEMPERATURE "INSTALLATION_TEMPERATURE"
#define HEATER_ERRORS_RESET "HEATER_ERRORS_RESET"
#define HEATER_RELEASE "HEATER_RELEASE"

#define VOLUME "VOLUME"
#define AUTOMATIC_ADJUSTMENT_BRIGHTNESS "AUTOMATIC_ADJUSTMENT_BRIGHTNESS"
#define BRIGHTNESS "BRIGHTNESS"
#define LANGUAGE_CHANGE "LANGUAGE_CHANGE"
#define DASH_BOARD_LEFT_ACTIVE "DASH_BOARD_LEFT_ACTIVE"

#define INSTALLATION_TEMPERATURE "INSTALLATION_TEMPERATURE"
#define HEATER_ERRORS_RESET "HEATER_ERRORS_RESET"
#define HEATER_RELEASE "HEATER_RELEASE"

#define CLIMATE_INSTALLATION_TEMPERATURE "CLIMATE_INSTALLATION_TEMPERATURE"
#define CLIMATE_CONTROL_DRIVER_CAB_LEFT_ACTIVE "CLIMATE_CONTROL_DRIVER_CAB_LEFT_ACTIVE"

#define SENSOR_SENSITIVITY_RAIN "SENSOR_SENSITIVITY_RAIN"
#define SENSOR_SENSITIVITY_LIGHT "SENSOR_SENSITIVITY_LIGHT"
#define LIGHT_RAIN_SENSOR_LEFT_ACTIVE "LIGHT_RAIN_SENSOR_LEFT_ACTIVE"

#define AUTOMATIC_LOW_BEAM "AUTOMATIC_LOW_BEAM"
#define AUTOMATIC_WIPER_OPERATION "AUTOMATIC_WIPER_OPERATION"
#define SENSOR_SENSITIVITY_TO_RAIN "SENSOR_SENSITIVITY_TO_RAIN"
#define SENSOR_SENSITIVITY_TO_LIGHT "SENSOR_SENSITIVITY_TO_LIGHT"

#define INSTALLATION_TEMPERATURE_CLIMATE_CONTROL "INSTALLATION_TEMPERATURE_CLIMATE_CONTROL"
#define COOLANT_DAMPER "COOLANT_DAMPER"
#define AIR_INTAKE "AIR_INTAKE"
#define AIR_INTAKE_FROM_INSIDE "AIR_INTAKE_FROM_INSIDE"

#define DOOR_MANAGEMENT "DOOR_MANAGEMENT"
#define AUTOMATIC_OPENING "AUTOMATIC_OPENING"
#define AUTOMATIC_DOOR_CLOSING_BY_SENSORS "AUTOMATIC_DOOR_CLOSING_SENSORS"
#define AUTOMATIC_DOOR_CLOSING_WHEN_LEAVING_THE_BUS "AUTOMATIC_DOOR_CLOSING_WHEN_LEAVING_THE_BUS"
#define AUTOMATIC_KNEELING "AUTOMATIC_KNEELING"
#define AUTOMATIC_ON_OF_THE_ALARM_SYSTEM "AUTOMATIC_ON_OF_THE_ALARM_SYSTEM"
#define DOORWAY_PASSENGER_SENSOR "DOORWAY_PASSENGER_SENSOR"

#define WIPERS_SERVICES "WIPERS_SERVICES"
#define SERVICE_MODE "SERVICE_MODE"
#define SETTINGS_THE_NO_OPERATIONS_TO_ZERO "SETTINGS_THE_NO_OPERATIONS_TO_ZERO"

#define DIGANOSTIC_TROUBLE_CODE "DIGANOSTIC_TROUBLE_CODE"
#define NO_TROUBLE_CODE "NO_TROUBLE_CODE"
#define DTC_GROUP_COUNT "DTC_GROUP_COUNT"

#define PROPULSION_SYSTEM_DTC "PROPULSION_SYSTEM_DTC"
#define PROPULSION_SYSTEM_DTC_COUNT "PROPULSION_SYSTEM_DTC_COUNT"
#define PROPULSION_SYSTEM_DTC1 "PROPULSION_SYSTEM_DTC1"
#define PROPULSION_SYSTEM_DTC2 "PROPULSION_SYSTEM_DTC2"
#define PROPULSION_SYSTEM_DTC3 "PROPULSION_SYSTEM_DTC3"
#define PROPULSION_SYSTEM_DTC4 "PROPULSION_SYSTEM_DTC4"
#define PROPULSION_SYSTEM_DTC5 "PROPULSION_SYSTEM_DTC5"

#define TRANSMISSION_DTC "TRANSMISSION_DTC"
#define TRANSMISSION_DTC_COUNT "TRANSMISSION_DTC_COUNT"
#define TRANSMISSION_SYSTEM_DTC1 "TRANSMISSION_SYSTEM_DTC1"
#define TRANSMISSION_SYSTEM_DTC2 "TRANSMISSION_SYSTEM_DTC2"
#define TRANSMISSION_SYSTEM_DTC3 "TRANSMISSION_SYSTEM_DTC3"
#define TRANSMISSION_SYSTEM_DTC4 "TRANSMISSION_SYSTEM_DTC4"
#define TRANSMISSION_SYSTEM_DTC5 "TRANSMISSION_SYSTEM_DTC5"

#define BRAKE_SYSTEM_DTC "BRAKE_SYSTEM_DTC"
#define BRAKE_SYSTEM_DTC_COUNT "BRAKE_SYSTEM_DTC_COUNT"
#define BRAKE_SYSTEM_DTC1 "BRAKE_SYSTEM_DTC1"
#define BRAKE_SYSTEM_DTC2 "BRAKE_SYSTEM_DTC2"
#define BRAKE_SYSTEM_DTC3 "BRAKE_SYSTEM_DTC3"
#define BRAKE_SYSTEM_DTC4 "BRAKE_SYSTEM_DTC4"
#define BRAKE_SYSTEM_DTC5 "BRAKE_SYSTEM_DTC5"

#define PNEUMATIC_SYSTEM_DTC "PNEUMATIC_SYSTEM_DTC"
#define PNEUMATIC_SYSTEM_DTC_COUNT "PNEUMATIC_SYSTEM_DTC_COUNT"
#define PNEUMATIC_SYSTEM_DTC1 "PNEUMATIC_SYSTEM_DTC1`"
#define PNEUMATIC_SYSTEM_DTC2 "PNEUMATIC_SYSTEM_DTC2`"
#define PNEUMATIC_SYSTEM_DTC3 "PNEUMATIC_SYSTEM_DTC3`"
#define PNEUMATIC_SYSTEM_DTC4 "PNEUMATIC_SYSTEM_DTC4`"
#define PNEUMATIC_SYSTEM_DTC5 "PNEUMATIC_SYSTEM_DTC5`"

#define TACHOGRAPH_DTC "TACHOGRAPH_DTC"
#define TACHOGRAPH_DTC_COUNT "TACHOGRAPH_DTC_COUNT"
#define TACHOGRAPH_SYSTEM_DTC1 "TACHOGRAPH_SYSTEM_DTC1"
#define TACHOGRAPH_SYSTEM_DTC2 "TACHOGRAPH_SYSTEM_DTC2"
#define TACHOGRAPH_SYSTEM_DTC3 "TACHOGRAPH_SYSTEM_DTC3"
#define TACHOGRAPH_SYSTEM_DTC4 "TACHOGRAPH_SYSTEM_DTC4"
#define TACHOGRAPH_SYSTEM_DTC5 "TACHOGRAPH_SYSTEM_DTC5"

#define TYRE_PRESSURE_MONITORING_SYSTEM_DTC "TYRE_PRESSURE_MONITORING_SYSTEM_DTC"
#define TYRE_PRESSURE_MONITORING_SYSTEM_DTC_COUNT "TYRE_PRESSURE_MONITORING_SYSTEM_DTC_COUNT"
#define TIRE_PRESSURE_MONITOR_SYSTEM_DTC1 "TIRE_PRESSURE_MONITOR_SYSTEM_DTC1"
#define TIRE_PRESSURE_MONITOR_SYSTEM_DTC2 "TIRE_PRESSURE_MONITOR_SYSTEM_DTC2"
#define TIRE_PRESSURE_MONITOR_SYSTEM_DTC3 "TIRE_PRESSURE_MONITOR_SYSTEM_DTC3"
#define TIRE_PRESSURE_MONITOR_SYSTEM_DTC4 "TIRE_PRESSURE_MONITOR_SYSTEM_DTC4"
#define TIRE_PRESSURE_MONITOR_SYSTEM_DTC5 "TIRE_PRESSURE_MONITOR_SYSTEM_DTC5"

#define ADDITIONAL_FUNCTIONALITY "ADDITIONAL_FUNCTIONALITY"
#define MOTION_DEBLOCKED "MOTION_DEBLOCKED"
#define TURBOTIMER "TURBOTIMER"

#define STEERING_ANGLE_SENSOR "STEERING_ANGLE_SENSOR"
#define N_DEGREE "N_DEGREE"
#define M_VALUE "M_VALUE"
#define STEERING_INSTRUCTIONS "STEERING_INSTRUCTIONS"
#define STEERING_ANGLE_STATUS "STEERING_ANGLE_STATUS"

#define DATA_SOURCE "DATA_SOURCE"
#define TEMPELATE1_DROPLIST "TEMPELATE1_DROPLIST"
#define TEMPELATE2_DROPLIST "TEMPELATE2_DROPLIST"
#define TEMPELATE3_DROPLIST "TEMPELATE3_DROPLIST"
#define TEMPELATE4_DROPLIST "TEMPELATE4_DROPLIST"
#define TEMPELATE5_DROPLIST "TEMPELATE5_DROPLIST"
#define TEMPELATE6_DROPLIST "TEMPELATE6_DROPLIST"

#define CHANGE_PASSWORD "CHANGE_PASSWORD"
#define PASSWORD "PASSWORD"
#define VALID_PASSWORD "VALID_PASSWORD"
#define NEW_PASSWORD "NEW_PASSWORD"
#define CONFIRMATION_PASSWORD "CONFIRMATION_PASSWORD"
#define PASSWORD_DATA "PASSWORD_DATA"

#define SOFTWARE_VERSION "SOFTWARE_VERSION"

#define EC12_SOFTWARE_VERSION "EC12"
#define CC_SOFTWARE_VERSION "CC"
#define REDP_SOFTWARE_VERSION "REDP"
#define RES_SOFTWARE_VERSION "RES"
#define CONFIG_DATA_FILE_NAME "../../Json/config_data.json"

#define DOOR_MANAGEMENT_HEADER "DOOR_MANAGEMENT"
#define WIPERS_SERVICES_HEADER "WIPERS_SERVICES"
#define DIGANOSTIC_TROUBLE_CODE_HEADER "DIGANOSTIC_TROUBLE_CODE"
#define ADDITIONAL_FUNCTIONALITY_HEADER "ADDITIONAL_FUNCTIONALITY"
#define STEERING_ANGLE_SENSOR_HEADER "STEERING_ANGLE_SENSOR"
#define DATA_SOURCE_HEADER "DATA_SOURCE"
#define CHANGE_PASSWORD_HEADER "CHANGE_PASSWORD"
#define SOFTWARE_VERSION_HEADER "SOFTWARE_VERSION"

#define NA_RANGE "NA:NA:NA"
#define MENU_NA_VALUE "NA"
#define VISIBILITY_FALSE "false"
#define VISIBILITY_TRUE "true"
#define INIT_MENU_VALUE "0"
#define INIT_VOLTAGE_VALUE "15"
#define INIT_MENU_DASHBOARD_VOLUME_VALUE "10 %"
#define INIT_MENU_DASHBOARD_BRIGHTNESS_VALUE "10 %"
#define INIT_COLOR "white"
#define STATE_CLOSE "CLOSE"
#define LANGUAGE_ENGLISH "ENGLISH"
#define LANGUAGE_RUSSIAN "RUSSIAN"

#define INSTALL_TEMPERATURE_RANGE "16:21:26"
#define VOLUME_RANGE "10:50:100"
#define BRIGHTNESS_RANGE "10:50:100"

#define LIGHT_SENSOR "LIGHT_SENSOR"
#define RAIN_SENSOR "RAIN_SENSOR"
#define SENSITIVITY_LEVEL_  QT_TR_NOOP("Sensitivity level")
#define SENSITIVITY_LEVEL_1 "Sensitivity level 1"
#define SENSITIVITY_LEVEL_2 "Sensitivity level 2"
#define SENSITIVITY_LEVEL_3 "Sensitivity level 3"
#define SENSITIVITY_LEVEL_4 "Sensitivity level 4"

#define SENSITIVITY_  QT_TR_NOOP("Sensitivity")
#define SENSITIVITY_0 "Sensitivity 0"
#define SENSITIVITY_1 "Sensitivity 1"
#define SENSITIVITY_2 "Sensitivity 2"
#define SENSITIVITY_3 "Sensitivity 3"
#define SENSITIVITY_4 "Sensitivity 4"
#define SENSITIVITY_5 "Sensitivity 5"

#define RAIN_SENSITIVITY_MIN_VALUE "1"
#define RAIN_SENSITIVITY_MAX_VALUE "4"
#define LIGHT_SENSITIVITY_MIN_VALUE "0"
#define LIGHT_SENSITIVITY_MAX_VALUE "5"

#define INSTALLATION_TEMPERATURE_CONFIG "installation_temperature"
#define VOLUME_CONFIG "volume"
#define AUTOMATIC_ADJUSTMENT_BRIGHTNESS_CONFIG "automatic_adjustment_brightness"
#define BRIGHTNESS_CONFIG "brightness"
#define LANGUAGE_CHANGE_CONFIG "language_change"
#define AUTOMATIC_LOW_BEAM_CONFIG "automatic_low_beam"
#define AUTOMATIC_WIPER_OPERATION_CONFIG "automatic_wiper_operation"
#define SENSOR_SENSITIVITY_TO_RAIN_CONFIG "sensor_sensitivity_to_rain"
#define SENSOR_SENSITIVITY_TO_LIGHT_CONFIG "sensor_sensitivity_to_light"
#define INSTALLATION_TEMPERATURE_DC_CONFIG "installation_temperature_DC"
#define AUTOMATIC_OPENING_CONFIG "automatic_opening"
#define AUTOMATIC_DOOR_CLOSING_BY_SENSORS_CONFIG "automatic_door_closing_by_sensors"
#define AUTOMATIC_DOOR_CLOSING_WHEN_LEAVING_BUS_CONFIG "automatic_door_closing_when_leaving_bus"
#define AUTOMATIC_KNEELING_CONFIG "automatic_kneeling"
#define AUTOMATIC_ON_OF_ALARM_SYSTEM_CONFIG "automatic_on_of_alarm_system"
#define DOORWAY_PASSENGER_SENSOR_CONFIG "doorway_passenger_sensor"
#define BRAKE_PADS_WEAR_1_2_CONFIG "brake_pads_wear_1_2"
#define NEW_PASSWORD_CONFIG "new_password"
#define PARAMETERIZATION_CONFIG "parameterization"

#define STATUS_OFF QT_TR_NOOP("OFF")
#define STATUS_ON QT_TR_NOOP("ON")
#define VALUE_ONE 1
#define VALUE_ZERO 0
#define TEST_LIGHT_EQUIPMENTS "TEST_LIGHT_EQUIPMENTS"
#define POSITION_LIGHTS "POSITION_LIGHTS"
#define LOW_BEAM "LOW_BEAM"
#define HIGH_BEAM "HIGH_BEAM"
#define TURN_SIGNALS "TURN_SIGNALS"
#define DLR "DLR"
#define FRONT_FOG_LAMP "FRONT_FOG_LAMP"
#define REAR_FOG_LAMP "REAR_FOG_LAMP"
#define REVERSE_LIGHTS "REVERSE_LIGHTS"
#define LIGHTS "LIGHTS"
#define BRIGHTNESS_MIN_VALUE 10
#define PATH_BRIGHTNESS_CONTROL "/sys/class/backlight/backlight/brightness"
#define WRITE_MODE "w"
#define READ_MODE "r"

// DD SETTINGS MACROS
#define SIGNLE_READ_Mask0 0U
#define SIGNLE_READ_Mask1 0x01U
#define SIGNLE_READ_Mask2 0x03U
#define SIGNLE_READ_Mask3 0x07U
#define SIGNLE_READ_Mask4 0x0FU
#define SIGNLE_READ_Mask5 0x1FU
#define SIGNLE_READ_Mask6 0x3FU
#define SIGNLE_READ_Mask7 0x7FU
#define SIGNLE_READ_Mask8 0xFFU

#define DD_SETTINGS_SENSORSPRESENCEPASSENGERDOORWAY_MASK0 1U
#define DD_SETTINGS_AUTOMATICONALARM_MASK0 2U
#define DD_SETTINGS_AUTOKNEELING_MASK0 3U
#define DD_SETTINGS_AUTOCLOSINGDRSWHENLEAVINGVEHICLE_MASK0 4U
#define DD_SETTINGS_AUTOCLOSINGDOORSBYSENSORS_MASK0 5U
#define DD_SETTINGS_AUTOMATICOPENING_MASK0 6U
#define DD_SETTINGS_RESERVE1_MASK0 7U
#define DD_SETTINGS_RESETNUMBERACTIVATIONS_MASK0 1U
#define DD_SETTINGS_REMOVINGTRAFFICBLOCKS_MASK0 2U
#define DD_SETTINGS_TURBOTIMER_MASK0 3U
#define DD_SETTINGS_RESERVE2_MASK0 4U
#define DD_SETTINGS_LOWBEAMHEADLIGHTS_MASK0 1U
#define DD_SETTINGS_HIGHBEAMHEADLIGHTS_MASK0 2U
#define DD_SETTINGS_DIRECTIONINDICATORS_MASK0 3U
#define DD_SETTINGS_DAYTIMERUNNINGLIGHTS_MASK0 4U
#define DD_SETTINGS_FOGLIGHTS_MASK0 5U
#define DD_SETTINGS_REARFOGLIGHTS_MASK0 6U
#define DD_SETTINGS_REVERSINGLIGHTS_MASK0 7U
#define DD_SETTINGS_RESERVE3_MASK0 1U
#define DD_SETTINGS_RESETHEATERERRORS_MASK0 3U
#define DD_SETTINGS_UNLOCKINGTHEHEATER_MASK0 4U
#define DD_SETTINGS_RAINSENSITIVITY_MASK0 5U
#define DD_SETTINGS_AUTOSETTINGSLOWBEAM_MASK0 3U
#define DD_SETTINGS_AUTOWIPERSETTINGSMODE_MASK0 4U

#define DD_SETTINGS_SETTINGADDRESSABLEDOORBUTTONSFACTOR (1)
#define DD_SETTINGS_CANID_SETTINGADDRESSABLEDOORBUTTONS_STARTBIT (0)
#define DD_SETTINGS_CANID_SETTINGADDRESSABLEDOORBUTTONS_OFFSET (0)
#define DD_SETTINGS_CANID_SETTINGADDRESSABLEDOORBUTTONS_MIN (0)
#define DD_SETTINGS_CANID_SETTINGADDRESSABLEDOORBUTTONS_MAX (1)
#define DD_SETTINGS_SENSORSPRESENCEPASSENGERDOORWAYFACTOR (1)
#define DD_SETTINGS_CANID_SENSORSPRESENCEPASSENGERDOORWAY_STARTBIT (1)
#define DD_SETTINGS_CANID_SENSORSPRESENCEPASSENGERDOORWAY_OFFSET (0)
#define DD_SETTINGS_CANID_SENSORSPRESENCEPASSENGERDOORWAY_MIN (0)
#define DD_SETTINGS_CANID_SENSORSPRESENCEPASSENGERDOORWAY_MAX (1)
#define DD_SETTINGS_AUTOMATICONALARMFACTOR (1)
#define DD_SETTINGS_CANID_AUTOMATICONALARM_STARTBIT (2)
#define DD_SETTINGS_CANID_AUTOMATICONALARM_OFFSET (0)
#define DD_SETTINGS_CANID_AUTOMATICONALARM_MIN (0)
#define DD_SETTINGS_CANID_AUTOMATICONALARM_MAX (1)
#define DD_SETTINGS_AUTOKNEELINGFACTOR (1)
#define DD_SETTINGS_CANID_AUTOKNEELING_STARTBIT (3)
#define DD_SETTINGS_CANID_AUTOKNEELING_OFFSET (0)
#define DD_SETTINGS_CANID_AUTOKNEELING_MIN (0)
#define DD_SETTINGS_CANID_AUTOKNEELING_MAX (1)
#define DD_SETTINGS_AUTOCLOSINGDRSWHENLEAVINGVEHICLEFACTOR (1)
#define DD_SETTINGS_CANID_AUTOCLOSINGDRSWHENLEAVINGVEHICLE_STARTBIT (4)
#define DD_SETTINGS_CANID_AUTOCLOSINGDRSWHENLEAVINGVEHICLE_OFFSET (0)
#define DD_SETTINGS_CANID_AUTOCLOSINGDRSWHENLEAVINGVEHICLE_MIN (0)
#define DD_SETTINGS_CANID_AUTOCLOSINGDRSWHENLEAVINGVEHICLE_MAX (1)
#define DD_SETTINGS_AUTOCLOSINGDOORSBYSENSORSFACTOR (1)
#define DD_SETTINGS_CANID_AUTOCLOSINGDOORSBYSENSORS_STARTBIT (5)
#define DD_SETTINGS_CANID_AUTOCLOSINGDOORSBYSENSORS_OFFSET (0)
#define DD_SETTINGS_CANID_AUTOCLOSINGDOORSBYSENSORS_MIN (0)
#define DD_SETTINGS_CANID_AUTOCLOSINGDOORSBYSENSORS_MAX (1)
#define DD_SETTINGS_AUTOMATICOPENINGFACTOR (1)
#define DD_SETTINGS_CANID_AUTOMATICOPENING_STARTBIT (6)
#define DD_SETTINGS_CANID_AUTOMATICOPENING_OFFSET (0)
#define DD_SETTINGS_CANID_AUTOMATICOPENING_MIN (0)
#define DD_SETTINGS_CANID_AUTOMATICOPENING_MAX (1)
#define DD_SETTINGS_RESERVEFACTOR (1)
#define DD_SETTINGS_CANID_RESERVE1_STARTBIT (7)
#define DD_SETTINGS_CANID_RESERVE1_OFFSET (0)
#define DD_SETTINGS_CANID_RESERVE1_MIN (0)
#define DD_SETTINGS_CANID_RESERVE1_MAX (1)
#define DD_SETTINGS_SERVECEMODEFACTOR (1)
#define DD_SETTINGS_CANID_SERVECEMODE_STARTBIT (8)
#define DD_SETTINGS_CANID_SERVECEMODE_OFFSET (0)
#define DD_SETTINGS_CANID_SERVECEMODE_MIN (0)
#define DD_SETTINGS_CANID_SERVECEMODE_MAX (1)
#define DD_SETTINGS_RESETNUMBERACTIVATIONSFACTOR (1)
#define DD_SETTINGS_CANID_RESETNUMBERACTIVATIONS_STARTBIT (9)
#define DD_SETTINGS_CANID_RESETNUMBERACTIVATIONS_OFFSET (0)
#define DD_SETTINGS_CANID_RESETNUMBERACTIVATIONS_MIN (0)
#define DD_SETTINGS_CANID_RESETNUMBERACTIVATIONS_MAX (1)
#define DD_SETTINGS_REMOVINGTRAFFICBLOCKSFACTOR (1)
#define DD_SETTINGS_CANID_REMOVINGTRAFFICBLOCKS_STARTBIT (10)
#define DD_SETTINGS_CANID_REMOVINGTRAFFICBLOCKS_OFFSET (0)
#define DD_SETTINGS_CANID_REMOVINGTRAFFICBLOCKS_MIN (0)
#define DD_SETTINGS_CANID_REMOVINGTRAFFICBLOCKS_MAX (1)
#define DD_SETTINGS_TURBOTIMERFACTOR (1)
#define DD_SETTINGS_CANID_TURBOTIMER_STARTBIT (11)
#define DD_SETTINGS_CANID_TURBOTIMER_OFFSET (0)
#define DD_SETTINGS_CANID_TURBOTIMER_MIN (0)
#define DD_SETTINGS_CANID_TURBOTIMER_MAX (1)
#define DD_SETTINGS_RESERVEFACTOR (1)
#define DD_SETTINGS_CANID_RESERVE2_STARTBIT (12)
#define DD_SETTINGS_CANID_RESERVE2_OFFSET (0)
#define DD_SETTINGS_CANID_RESERVE2_MIN (0)
#define DD_SETTINGS_CANID_RESERVE2_MAX (15)
#define DD_SETTINGS_PARKINGLIGHTSFACTOR (1)
#define DD_SETTINGS_CANID_PARKINGLIGHTS_STARTBIT (16)
#define DD_SETTINGS_CANID_PARKINGLIGHTS_OFFSET (0)
#define DD_SETTINGS_CANID_PARKINGLIGHTS_MIN (0)
#define DD_SETTINGS_CANID_PARKINGLIGHTS_MAX (1)
#define DD_SETTINGS_LOWBEAMHEADLIGHTSFACTOR (1)
#define DD_SETTINGS_CANID_LOWBEAMHEADLIGHTS_STARTBIT (17)
#define DD_SETTINGS_CANID_LOWBEAMHEADLIGHTS_OFFSET (0)
#define DD_SETTINGS_CANID_LOWBEAMHEADLIGHTS_MIN (0)
#define DD_SETTINGS_CANID_LOWBEAMHEADLIGHTS_MAX (1)
#define DD_SETTINGS_HIGHBEAMHEADLIGHTSFACTOR (1)
#define DD_SETTINGS_CANID_HIGHBEAMHEADLIGHTS_STARTBIT (18)
#define DD_SETTINGS_CANID_HIGHBEAMHEADLIGHTS_OFFSET (0)
#define DD_SETTINGS_CANID_HIGHBEAMHEADLIGHTS_MIN (0)
#define DD_SETTINGS_CANID_HIGHBEAMHEADLIGHTS_MAX (1)
#define DD_SETTINGS_DIRECTIONINDICATORSFACTOR (1)
#define DD_SETTINGS_CANID_DIRECTIONINDICATORS_STARTBIT (19)
#define DD_SETTINGS_CANID_DIRECTIONINDICATORS_OFFSET (0)
#define DD_SETTINGS_CANID_DIRECTIONINDICATORS_MIN (0)
#define DD_SETTINGS_CANID_DIRECTIONINDICATORS_MAX (1)
#define DD_SETTINGS_DAYTIMERUNNINGLIGHTSFACTOR (1)
#define DD_SETTINGS_CANID_DAYTIMERUNNINGLIGHTS_STARTBIT (20)
#define DD_SETTINGS_CANID_DAYTIMERUNNINGLIGHTS_OFFSET (0)
#define DD_SETTINGS_CANID_DAYTIMERUNNINGLIGHTS_MIN (0)
#define DD_SETTINGS_CANID_DAYTIMERUNNINGLIGHTS_MAX (1)
#define DD_SETTINGS_FOGLIGHTSFACTOR (1)
#define DD_SETTINGS_CANID_FOGLIGHTS_STARTBIT (21)
#define DD_SETTINGS_CANID_FOGLIGHTS_OFFSET (0)
#define DD_SETTINGS_CANID_FOGLIGHTS_MIN (0)
#define DD_SETTINGS_CANID_FOGLIGHTS_MAX (1)
#define DD_SETTINGS_REARFOGLIGHTSFACTOR (1)
#define DD_SETTINGS_CANID_REARFOGLIGHTS_STARTBIT (22)
#define DD_SETTINGS_CANID_REARFOGLIGHTS_OFFSET (0)
#define DD_SETTINGS_CANID_REARFOGLIGHTS_MIN (0)
#define DD_SETTINGS_CANID_REARFOGLIGHTS_MAX (1)
#define DD_SETTINGS_REVERSINGLIGHTSFACTOR (1)
#define DD_SETTINGS_CANID_REVERSINGLIGHTS_STARTBIT (23)
#define DD_SETTINGS_CANID_REVERSINGLIGHTS_OFFSET (0)
#define DD_SETTINGS_CANID_REVERSINGLIGHTS_MIN (0)
#define DD_SETTINGS_CANID_REVERSINGLIGHTS_MAX (1)
#define DD_SETTINGS_STOPSIGNALFACTOR (1)
#define DD_SETTINGS_CANID_STOPSIGNAL_STARTBIT (24)
#define DD_SETTINGS_CANID_STOPSIGNAL_OFFSET (0)
#define DD_SETTINGS_CANID_STOPSIGNAL_MIN (0)
#define DD_SETTINGS_CANID_STOPSIGNAL_MAX (1)
#define DD_SETTINGS_RESERVEFACTOR (1)
#define DD_SETTINGS_CANID_RESERVE3_STARTBIT (25)
#define DD_SETTINGS_CANID_RESERVE3_OFFSET (0)
#define DD_SETTINGS_CANID_RESERVE3_MIN (0)
#define DD_SETTINGS_CANID_RESERVE3_MAX (3)
#define DD_SETTINGS_RESETHEATERERRORSFACTOR (1)
#define DD_SETTINGS_CANID_RESETHEATERERRORS_STARTBIT (27)
#define DD_SETTINGS_CANID_RESETHEATERERRORS_OFFSET (0)
#define DD_SETTINGS_CANID_RESETHEATERERRORS_MIN (0)
#define DD_SETTINGS_CANID_RESETHEATERERRORS_MAX (1)
#define DD_SETTINGS_UNLOCKINGTHEHEATERFACTOR (1)
#define DD_SETTINGS_CANID_UNLOCKINGTHEHEATER_STARTBIT (28)
#define DD_SETTINGS_CANID_UNLOCKINGTHEHEATER_OFFSET (0)
#define DD_SETTINGS_CANID_UNLOCKINGTHEHEATER_MIN (0)
#define DD_SETTINGS_CANID_UNLOCKINGTHEHEATER_MAX (1)
#define DD_SETTINGS_RAINSENSITIVITYFACTOR (1)
#define DD_SETTINGS_CANID_RAINSENSITIVITY_STARTBIT (29)
#define DD_SETTINGS_CANID_RAINSENSITIVITY_OFFSET (0)
#define DD_SETTINGS_CANID_RAINSENSITIVITY_MIN (0)
#define DD_SETTINGS_CANID_RAINSENSITIVITY_MAX (7)
#define DD_SETTINGS_INSTALLATIONTEMPERATUREFACTOR (1)
#define DD_SETTINGS_CANID_INSTALLATIONTEMPERATURE_STARTBIT (32)
#define DD_SETTINGS_CANID_INSTALLATIONTEMPERATURE_OFFSET (0)
#define DD_SETTINGS_CANID_INSTALLATIONTEMPERATURE_MIN (0)
#define DD_SETTINGS_CANID_INSTALLATIONTEMPERATURE_MAX (255)
#define DD_SETTINGS_DRIVERINSTALLATIONTEMPERATUREFACTOR (1)
#define DD_SETTINGS_CANID_DRIVERINSTALLATIONTEMPERATURE_STARTBIT (40)
#define DD_SETTINGS_CANID_DRIVERINSTALLATIONTEMPERATURE_OFFSET (0)
#define DD_SETTINGS_CANID_DRIVERINSTALLATIONTEMPERATURE_MIN (0)
#define DD_SETTINGS_CANID_DRIVERINSTALLATIONTEMPERATURE_MAX (255)
#define DD_SETTINGS_SENSITIVITYTOLIGHTFACTOR (1)
#define DD_SETTINGS_CANID_SENSITIVITYTOLIGHT_STARTBIT (48)
#define DD_SETTINGS_CANID_SENSITIVITYTOLIGHT_OFFSET (0)
#define DD_SETTINGS_CANID_SENSITIVITYTOLIGHT_MIN (0)
#define DD_SETTINGS_CANID_SENSITIVITYTOLIGHT_MAX (7)
#define DD_SETTINGS_AUTOSETTINGSLOWBEAMFACTOR (1)
#define DD_SETTINGS_CANID_AUTOSETTINGSLOWBEAM_STARTBIT (51)
#define DD_SETTINGS_CANID_AUTOSETTINGSLOWBEAM_OFFSET (0)
#define DD_SETTINGS_CANID_AUTOSETTINGSLOWBEAM_MIN (0)
#define DD_SETTINGS_CANID_AUTOSETTINGSLOWBEAM_MAX (1)
#define DD_SETTINGS_AUTOWIPERSETTINGSMODEFACTOR (1)
#define DD_SETTINGS_CANID_AUTOWIPERSETTINGSMODE_STARTBIT (52)
#define DD_SETTINGS_CANID_AUTOWIPERSETTINGSMODE_OFFSET (0)
#define DD_SETTINGS_CANID_AUTOWIPERSETTINGSMODE_MIN (0)
#define DD_SETTINGS_CANID_AUTOWIPERSETTINGSMODE_MAX (1)

#define ROUND_TO_NEAR_MULTIPLE_FACTOR_10 (10)
#define ROUND_TO_NEAR_MULTIPLE_FACTOR_1 (1)
#define ROUND_TO_NEAR_MULTIPLE_FACTOR_0 (0)

#define MINIMUM_INSTALLATION_TEMPERATURE 16
#define MAXIMUM_INSTALLATION_TEMPERATURE 26

#define MINIMUM_VALUE_SENSITIVITY_LIGHT 0
#define MAXIMUM_VALUE_SENSITIVITY_LIGHT 5

#define MINIMUM_VALUE_SENSITIVITY_RAIN 1
#define MAXIMUM_VALUE_SENSITIVITY_RAIN 4

#define BRIGHTNESS_VALUE_10 27
#define BRIGHTNESS_VALUE_20 37
#define BRIGHTNESS_VALUE_30 47
#define BRIGHTNESS_VALUE_40 57
#define BRIGHTNESS_VALUE_50 67
#define BRIGHTNESS_VALUE_60 77
#define BRIGHTNESS_VALUE_70 87
#define BRIGHTNESS_VALUE_80 97
#define BRIGHTNESS_VALUE_90 107
#define BRIGHTNESS_VALUE_100 127

//#define BRIGHTNESS_VALUE_2 2
//#define BRIGHTNESS_VALUE_3 3
//#define BRIGHTNESS_VALUE_4 4
//#define BRIGHTNESS_VALUE_5 5
//#define BRIGHTNESS_VALUE_6 6
//#define BRIGHTNESS_VALUE_7 7

#define BRIGHTNESS_COMPARE_VALUE_10 10
#define BRIGHTNESS_COMPARE_VALUE_20 20
#define BRIGHTNESS_COMPARE_VALUE_30 30
#define BRIGHTNESS_COMPARE_VALUE_40 40
#define BRIGHTNESS_COMPARE_VALUE_50 50
#define BRIGHTNESS_COMPARE_VALUE_60 60
#define BRIGHTNESS_COMPARE_VALUE_70 50
#define BRIGHTNESS_COMPARE_VALUE_80 80
#define BRIGHTNESS_COMPARE_VALUE_90 90
#define BRIGHTNESS_COMPARE_VALUE_100 100
#endif // MENU_DEFINES_H
